<a href="https://colab.research.google.com/github/erpyjune/deeptest/blob/main/tensor2test1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf

tensor = tf.constant([3,4,5])
tensor2 = tf.constant([6,7,8])
print(tensor + tensor2)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [6]:
import tensorflow as tf

tensor = tf.constant([
                      [1,2],[3,4] ] )
print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [8]:
import tensorflow as tf

tensor = tf.constant([ [3,4,5], [1,2,3] ])
tensor2 = tf.constant([6,7,8])
print(tensor * tensor2)

tf.Tensor(
[[18 28 40]
 [ 6 14 24]], shape=(2, 3), dtype=int32)
