<a href="https://colab.research.google.com/github/erpyjune/deeptest/blob/main/tensor2test1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import tensorflow as tf

tensor = tf.constant([3,4,5]) # 상수 선언
tensor2 = tf.constant([6,7,8])
print(tensor + tensor2)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)


In [18]:
import tensorflow as tf

tensor = tf.constant([
                      [1,2],[3,4] ] )
print(tensor)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [8]:
import tensorflow as tf

tensor = tf.constant([ [3,4,5], [1,2,3] ])  # 상수
tensor2 = tf.constant([6,7,8])
print(tensor * tensor2)

tf.Tensor(
[[18 28 40]
 [ 6 14 24]], shape=(2, 3), dtype=int32)


In [14]:
import tensorflow as tf

tensor = tf.zeros(100) # 0값으로 100개 만들기
tensor2 = tf.zeros([7,6]) # 7, 6 행렬 0으로 채워 넣기
tensor3 = tf.zeros([3,4])
tensor4 = tf.zeros([3,4,5])
print(tensor)
print(tensor2)
print(tensor3)
print(tensor4)
print(tensor4.shape)

tf.Tensor(
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.], shape=(100,), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(7, 6), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
(3, 4, 5)


In [19]:
import tensorflow as tf

w = tf.Variable(0) # 변수 선언 & 초기값
w2 = tf.Variable(1.0) # 변수 선언 & 초기값

# tensor value
print(w, w2)


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [20]:
import tensorflow as tf

w = tf.Variable(3.14) # 변수 선언 & 초기값
w2 = tf.Variable(5.77) # 변수 선언 & 초기값

# 일반적인 값으로 불러올수 있다.
print(w.numpy(), w2.numpy())


3.14 5.77
